### ISSUE TITLE
Question on handling collections

### ISSUE THREAD

**Issue by iacobson** [ecsx-framework/ECSx#49]
Hi, 
sorry for what may not be the most appropriate way to ask library questions (opening an issue). Please feel free to close it if it's not relevant.

As somebody working also on an ECS library with Elixir (https://github.com/iacobson/ecspanse, still WIP and not well documented ) I immediately read your [article](https://dockyard.com/blog/2023/07/06/ecsx-a-new-approach-to-game-development-in-elixir) and much of the docs of the library.

BTW, congrats! Such a nice and clean API.

However, one of my most significant issues with ECS in general is handling collections.

For example, let's say in the Ship game, the ship has a ridiculous amount of cannons, eg. 50. Each cannon can fire individually, and each cannon has a cooldown (as in your game).

What I'm thinking:
1. Create multiple (50) `Components.Cannon` and `Components.AttackCooldown` components for the same entity. 
I saw the `unique: false` option in the Components.
But how to know which one of them fired or is reloaded?
More than this, let's assume that each cannon damage can be upgraded, so it is important that cannon 15 is reloading but cannon 23 is available, for example.

2. Cannons are their own entities
They will hold components like `Components.AttackCooldown` and `Components.CannonDamage`.
But in this case, how to link the cannon entities with the ship entity.

Thank you! And looking forward to the future of this library.

**Comment by APB9785** [comment]
Hi @iacobson and thanks for your interest in ECSx!  For your situation, the proper way to handle this is for each cannon to be its own entity.  In the tutorial project, ships always have one cannon - no more, no less - so we are considering that cannon a part of the ship.  Therefore it is suitable to model cannon data as components of the ship.  For example, the AttackDamage of a cannon will always be the same for any cannon on the ship (since there can only be one), therefore we can say AttackDamage is an attribute of the ship.

However, as the game expands, such as adding arbitrary amounts of cannons, it becomes clear that it's not really the ship which has an AttackDamage, but it's the cannon.  And each cannon on a ship could have a totally different amount of damage.  So in this model, each cannon is an entity, and components such as AttackDamage, AttackRange, possibly even targets and cooldowns, will be attached to those cannons, instead of the ship.

You asked in this case how to link the ships with the cannons.  Remember that in ECS pretty much everything is a component;  associations are the same.  If it helps, you can think of entities like a row in a relational database, and components are the fields which make up the row.  What we need here is a foreign key - a component which holds the ID of another entity.  So you can do `mix ecsx.gen.component ParentShip binary` (assuming you're using UUIDs for entities) and then whenever a ship gets a new cannon (including the first one) be sure to `ParentShip.add(cannon, ship, ...)` to link the two.

Hope this helps!  Let me know if you have any other questions.

**Comment by iacobson** [comment]
Thanks for the detailed answer. Makes sense.
So in this example, you could not query the "Ship has many Cannons" but you could actually query "Cannon belongs to a Ship".

So let's say in the client (frontend) you would like to get all cannons only of your ship and display their damage value. 
You could do something like (pseudo):
```
cannon_entity_ids = 
ParentShip.all()
|> filter( component_value == ship_entity_id)
|> map(entity_id)
```

Then iterate over this list and  get each component like `CannonDamage.get_one(cannon_entity_id)`

Is that how it would work?

And another question, in the case of components with `unique: false`, how is the update done?

Thank you.

**Comment by APB9785** [comment]
For the first question, the answer is [`search/1`](https://hexdocs.pm/ecsx/ECSx.Component.html#c:search/1) e.g.
```elixir
cannon_entity_ids = ParentShip.search(ship_entity_id)
```

For the second question, right now the `update/2` function only works for unique components.  Therefore to make an update, you will have to use two steps:
```elixir
MyComponent.remove_one(entity, old_value)
MyComponent.add(entity, new_value, ...)
```
Possibly in a future version we could expose something like `update_one(entity, old_value, new_value)` for a convenience.  In the meantime, if you really want that done in one line, you could add the function yourself into the appropriate component module:
```elixir
# lib/my_app/components/my_nonunique_component.ex

defmodule MyApp.Components.MyNonuniqueComponent do

...

  def update_one(entity, old, new, opts \\ []) do
    MyNonuniqueComponent.remove_one(entity, old)
    MyNonuniqueComponent.add(entity, new, opts)
  end
end
```

**Comment by iacobson** [comment]
Thank you
