### ISSUE TITLE
How to run multiple instances?

### ISSUE THREAD

**Issue by bumbus** [ecsx-framework/ECSx#57]
Really a cool project, I like it very much!

I wonder if it would be possible to run multiple instances in one application?
Is that possible? Or how would you implement for example a platform where players could create and play their (own) games? In this scenario I would have to launch an own server/node for each game, right? Or is there an other way to do it?

**Comment by APB9785** [comment]
Hi @bumbus and thanks for your interest in ECSx!

> I wonder if it would be possible to run multiple instances in one application?  Is that possible?

Currently it is not possible to run multiple ECSx instances in one application.  But this is something which has been discussed before.  Here are a few takeaways:

* Multiple games can be run within the same ECSx instance.  For this, you'll create relationship entities to link players to the game they are playing.  These entities could have, for example, a `Player` component which stores the player's ID, and a `Game` component which stores the game's ID.
* One downside to running multiple games like this is that you cannot monitor them separately with [ECSx LiveDashboard](https://github.com/ecsx-framework/ecsx_live_dashboard).  Therefore, we are considering different implementations for allowing multiple ECSx instances in one app.
* Deploying multiple instances each with a separate server/node might be the best solution for some cases

> Or how would you implement for example a platform where players could create and play their (own) games?

The main limitation here is that ECSx is designed for component types and systems to be defined at compile-time.  Therefore, you can create an interface where players can build entities, but they must be made out of pre-defined component types, and relying on the existing systems you have already created for them.  Hypothetically you could include a `RunUserCode` system which fetches user-provided code out of memory somewhere and runs it, but this is dangerous because the user's code could include bugs or even be malicious, bringing down the entire app.
