### ISSUE TITLE
Is there a way to delete an Entity?

### ISSUE THREAD

**Issue by Binsect** [ecsx-framework/ECSx#84]
The current method is to use component removal.
```
 def destroy(entity) do
    ArmorRating.remove(entity)
    AttackCooldown.remove(entity)
    ...
  end
```

Is there a way to remove an entity so that all its associated components are removed?

**Comment by APB9785** [comment]
Hi @binsect and thanks for your interest in ECSx!  We have not implemented this as an "official" function because for many use cases, entities never get removed entirely.  They might have most of their components removed, as in the ship tutorial, but they will still hold some components such as `DestroyedAt`, `LastSeenLocation`, or `RespawnAt` in the cases of ships blowing up, players logging out, or mobs being slain.

But if you do have a case where you want to remove ALL components from an entity, you can implement this function as such:
```elixir
defmodule YourApp do
  ...
  def delete_ecsx_entity(entity) do
    for component_type <- YourApp.Manager.components() do
      component_type.remove(entity)
    end
  end
end
```
